# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
    ]
